### ISSUE TITLE
ModuleNotFoundError: No module named 'ERsampled'

### ISSUE THREAD

**Issue by AIunusual** [totilas/muffliato#1]
Thank you very much for your great research work.
I got the following error when I tried to run gd.py
"import private

    from ERsampled import eps_random, eps_global
ModuleNotFoundError: No module named 'ERsampled'"
I guess the ERsampled file is missing.
Thank you very much for any comments.

**Comment by totilas** [comment]
Thank for pointing that a file was missing, [this](https://github.com/totilas/muffliato/commit/b72cc1a09ad96440f405503939e2ba5a39a123e8) should the issue.
